# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d758569c785836879b21ec0880f470c80121f65feec0b06b9dbc43d1bb43559c53d25300349a2b23a5830609d3201dc69017fc6b1763b3f41d7f806e09018f3

test:
  secret_key_base: a26972dbc33bdf7ccdb3f1c64552ef7bc706a13434f353d814f6ceba8afc307c50d0ff180ab863ac5557553a1573b3d4e59ffaf6521e6c04127f8551a140aab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
